script: make travis
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: a5V8FJYqBb5L10XLTDtlbMH0cO3beN/ww4m5MR9A2g41xSDE11DartkpEEOxiAlEMHrJsVO/26FXzFCUyRiXLx/ZpncEz7wrjIxTfRGZ4vG9RnPDbZU+W/VZiuH7hXVi2iOYa715jphv3l7kEACjdR5d+psnNkmcIinbSV3mxbOFookUPQBQb6zXOPf8qOPx3aiEekBLEES0uDrId9g2/PuIACBwYGsEV64c5fU4nxOZ3OrZ4+0T0tGE482ZtC2V7z1cC6P0Avtg/+rA7Uo3J9Hy1Hrzxu+mgXcSbJCF1ryjlIYvEZM+r4I7IgWAkXHrFP4hEkv0WHja/wfdKUel26TPsZ8NyAlwXJtpO5VZRybZl8s/GIbkik6ejCvb2StczYKLpd++LdaY15AxrQzArPTKnu9++CsSUOxdyLM8Bf2Px1NpXX7KlkfGwrLJu5iCe1vCn25o1lmrlN5G82ulixeCv/VY3AUlq7HepnGlQYUP3o1SA04GS1OWUeWoz5go4GTiuA6HXEMAS50v3gR5KSmezDwLXUbYk8tqVXT9u4v22eGx4IRL2OCbL/leY4IGUWeljZG3bZZbjD/4ovD+ARjjK4uP1QN51C28YEBK5C9gnS8W3FVNvmE7NNVoT9O55LWGcmdirbzrrvfQkURuhPCNTEIvtaF8u//OF+543dc=
branches:
  only:
  - master
