script: make travis
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: ottXm+K2MMj5Xr/3GSwUx29Ln5wVXKtUSIzDdDxC/K9dq0BB8GK/aMKFGVz0j3zoTQR7W8LI7EUBmkvhIVhP0CiRh+/cXih7pCfqbhZ5M2RE4PW+TXmbYK5yJxQmjtVO7IbjRiGaw/IO3tX36wn9UxlS11NLufr+TxutmbCInXq4xSU/P2oNt58zOO9LsNmZ0AB9JtFHq9R4u8f1Wx05nKiTbT+JzeaLLC1KuUNRN6V3dANWqFwV7DCvETF363n80DNHt37F/n3Nyq7SA3VFFsbAYtc/TaStA8XxnZ8aX2jOz27pz48Mv58SdD8IJ1UbrP++W1AhBI7qVog5N3+1Mi14szNqzE295NQZmNIdY5sfej7QUiJammdsy4qVvQeh0ANlJtzecUAIL2Rx41c3pKujBvXOc0C2mogNalwsC9h0S2c1t1H4PqckSfgH5KyZiPk0kw9F4lDHeRJ4IEbk6rRbgN2Nz/AjsRXPyxyTnNqC6oWfKRD89XSWTICrEgKdIsT+4dAWM5IpOUQ+SLZsplWRQbOFdj+H97hiR198HKbIgBdaYd7exXKf6iaxfArVNhi5LTTVi6+1LIHyDCAh6YYapXrdbGyljR6H7m0TrSzxJlPUYPkc4bJpIyjFhSYW85bk09SMSopo6wEyDRqy/EofopPBfstGe+5knRGEBfE=
branches:
  only:
  - master
