script: make travis
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: iWM/Q/aaRdMIHeBBPn3Cb3FuwfE5nisdIhzCcPp9+71jiIR3120pzpM1eKY6cQXgjAjFrUEqZbbF7jtjsRosQYX/aBxDeftj+pw/sqfZnr9K2AR2Bc+laBBO1CLh2p8OelWbiGCpBYwQ4a9dcXsqzq6Ckor610NlEoAlb4J/UkY9RdYMclYaYjv6f0TNTjsY8kmIsFc9KbbaLy2vjMByQOdfZwgkwk35XJgTM8Z2QEC6flzbwiis9A4BXLjv3qcZTzHdREQ0MdtXKqQFJ5IWpvekHnLZH3DB6hL+KdnYpQ6Oav4pAg2F/dfOHELq2kKCVuLguKcJbQ8Z87seIgwo/ytDKPADvbGwMjbHFQbDbT98/hG6eWnZPhqTOrFpLSj9M5ozR4WqzYkewgwf1ypwx3HdRDLnDxc0tPqsf3mCf8shbejTbW0TFHaBLGdp8v2RbcouodPMtqw3b/axuEKisbAtEdLSvaAYfj/aElj+VzLyLLaZEVJLjt4e0ynWZIjNP1popkOuXdQuYxJ4JFTwMS8d5+FPuyzDd2sfcFY3N3CjQYZOg2KKrGf7YZIiVYbgxyqHL6wM3tLmPUHDNPIRY8IAKkT3RtJKJKeuQZSZH+At1mshj/9UROf61UbG7SY4BKpcCCWWs9GRVBdidOgqG68CIkqXjzgQziws8oQ8EVs=
branches:
  only:
  - master
