script: make travis
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: clFkhvuklCQQFrVewR135CCaLnWO26ukOEcK2UAyPIjExN2xfwX4eh2ECw5/H6arPKsC7YvVG/gJutu1cOfdrJb3PSR5zRT+H+eTQgUw/UAMvWB7Mewme1+FDu6XpVt8ipo/jLzfYblzmJQ4ZtZYKL8YKMhMWm0TRb7C9KG05tYMDmRTKqkq5m4t4ao3hfpF9d6EKcoo3KHM4Mp/ldaXlEPsfX70oiHD7lrxb6a7M5tw3IHuzUKsvSUfiVmv72jHcq2ZowY0ZxjeUxCFvlesdn0vUC51vGUd3Dgs/aFL9TRni4rnFoJe6CY29wrIwbO9Tb3LLGpXEkjEzZwYDEv6r8Z8d2b/og/zfXl9oa2B5eLbmaSg9gGrU9SZonBwTnXQTPMThCDMzo2VEBYgK5z/gl8wxDS9nbk1sIdP4VpJWV+CS0urnKS/JgsLH7OAGVFDhT1xwnr/5gseGEb4Yvy7tUw+k4M/2g32ZAHyaCngkQWpR2MqL8xx2KJEQr9AKjnMrUnNhKX2+N/kxXOP3pqU76XfvxH3pzc7lH64ZVGjUuPhZ6vGmHwdelmYJB14KwI10zdq+cNgKFuAEEGMu5V0I6LWXH9x4DywYGIPq4QRONQgqORB8DSA68IjHQSZahClApqNXKAY9BY8PYkk1ipGM6q0W/Tl0xdCjUoLaJfx0zA=
branches:
  only:
  - master
