script: make travis
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: travis@travis-ci.org
  - secure: T6TLBgrLm1/Wv+ISOfmAhfFjtrKUdsK8inOXufwq3lOqOgAP58z2XUL8gl0tn9vbTldWIAQ3nA5izHTikvCm4o8N1dEefvWiq2tI0Bec5DKdo8q6zthlfD5MKUc3PZZez/vl8LE3RIUob2/BrmewebB9hrev0aoj1JKieAredri99J8nJAvwbTlAc0gI7h41GobwehFsYqTZ7Suzw9UJAP8VFN/UwwzCZFu3TFxuFuqU97v1QF2/UHbURwiXIyxTZsmwprQzSh/D4SdeU4LkLQ7ImtThsJOiVtl659plQ4CtLW6BQzpvstRUB4+FEi8INmOl1n2lutd5tB6c937sc2H+1f/vIJJ3F+apSGPM7kjN3e9o9JPk/hwWb+R9q3ajvHm/U0kb6ZPpDYXQps4eN8Ecc8KqmU5YMaXGc/tYjP45nX9Sc42KK5uM8NWZV5K0Od+tslwwQqVxwT54s8bEXiUaMSS6K2+9kKAHCr8/jnV00T0JMW0zQsBiBMZsnLvsyxumA0kMRp4eYemeYIVOsP0ug62Bsqm5Tb4UAdSnuS+u2rJguN6J4pHnf0Pr52D6IYS/w+Zjg5mQ3Q1rmIH5sTpyTjEOJoJISfCiAfuEIqa5NXrqHClcAdUb0XQetT/B+qcGQeLBnhdDVA4stHhzcK3LEqkBoKYsKpK6Ze/uGQk=
branches:
  only:
  - master
