# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sky Poker
email: david.litvak@contentful.com
description: >
  Play Poker online, on tablet &amp; on mobile at Sky Poker.
  New customers get £10 completely free, plus a 200%
  matched first deposit bonus up to £500!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sky.poker"
host: 0.0.0.0

  # Build settings
markdown: kramdown

contentful:
  spaces:
    - links:
        space: 3fwy09k2gc9g
        access_token: 25f513e34e33916336bba1d740d135035d4e1d63b87fc446da374fec3aaccaca
    - poker:
        space: wqqfbf5k1yo4
        access_token: 666d20550b34a21e997519c52d9e8c4aceb6b022b5dbb3260935ff3af39e1542
